// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ndoxbegwzykmrfelycmz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5kb3hiZWd3enlrbXJmZWx5Y216Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMjQ0NDcsImV4cCI6MjA2NjYwMDQ0N30.x6Nghs7CqU5j2vd-SbVPPoSjouYsZ3V1y4qhwCV86m8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);